-- Script DDL: CentroMedicoSanRafael

CREATE TABLE Paciente (
    id_paciente      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rut              VARCHAR2(12) NOT NULL UNIQUE,
    nombre           VARCHAR2(100) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    direccion        VARCHAR2(150),
    telefono         VARCHAR2(20)
);

CREATE TABLE Medico (
    id_medico    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rut          VARCHAR2(12) NOT NULL UNIQUE,
    nombre       VARCHAR2(100) NOT NULL,
    especialidad VARCHAR2(50) NOT NULL
);

CREATE TABLE Cita (
    id_cita     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha       DATE NOT NULL,
    motivo      VARCHAR2(200),
    id_paciente NUMBER NOT NULL,
    id_medico   NUMBER NOT NULL,
    CONSTRAINT fk_cita_paciente FOREIGN KEY (id_paciente) REFERENCES Paciente(id_paciente),
    CONSTRAINT fk_cita_medico FOREIGN KEY (id_medico) REFERENCES Medico(id_medico)
);

CREATE TABLE Tratamiento (
    id_tratamiento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion    VARCHAR2(200) NOT NULL,
    fecha_inicio   DATE NOT NULL,
    fecha_fin      DATE,
    id_cita        NUMBER NOT NULL,
    CONSTRAINT fk_tratamiento_cita FOREIGN KEY (id_cita) REFERENCES Cita(id_cita)
);

CREATE TABLE Factura (
    id_factura   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha        DATE NOT NULL,
    monto_total  NUMBER(12,2) NOT NULL,
    id_cita      NUMBER NOT NULL,
    CONSTRAINT fk_factura_cita FOREIGN KEY (id_cita) REFERENCES Cita(id_cita)
);
